"""write simple sqlalchemy models without their functions and classmethods

Revision ID: 90e9ccdd25d8
Revises: 9b6af026d095
Create Date: 2024-10-17 22:36:22.367687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e9ccdd25d8'
down_revision = '9b6af026d095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('stock_code', sa.Text(), nullable=False),
    sa.Column('stock_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('stock_code'),
    sa.UniqueConstraint('stock_code')
    )
    op.create_table('enters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.Text(), nullable=False),
    sa.Column('user_username', sa.Text(), nullable=False),
    sa.Column('stock_value', sa.Text(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.stock_code'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.Text(), nullable=False),
    sa.Column('user_username', sa.Text(), nullable=False),
    sa.Column('stock_value', sa.Text(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.stock_code'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wish_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_username', sa.Text(), nullable=False),
    sa.Column('stock_code', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.stock_code'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_username', sa.Text(), nullable=False),
    sa.Column('enter_id', sa.Integer(), nullable=False),
    sa.Column('exit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enter_id'], ['enters.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['exit_id'], ['exits.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('trades')
    op.drop_table('wish_list')
    op.drop_table('exits')
    op.drop_table('enters')
    op.drop_table('stocks')
    # ### end Alembic commands ###
